In [1]:
import argparse
import os
import sys

import tqdm
import torch
import yaml

from connect4_mcts import coach
from connect4_mcts import policy

In [2]:
m = policy.Model(128, 10, 1e-3, 'cpu')

In [3]:
c = coach.Coach(m, 20000)

In [4]:
c.generate_games(1, 1.44, 40, 0)

(1, 4, 6, 7)
(1, 4, 6, 7)
(1, 4, 6, 7)
(1, 4, 6, 7)
(1, 4, 6, 7)
(1, 4, 6, 7)
(1, 4, 6, 7)
(1, 4, 6, 7)
(1, 4, 6, 7)
(1, 4, 6, 7)
(1, 4, 6, 7)
(1, 4, 6, 7)
(1, 4, 6, 7)
(1, 4, 6, 7)
(1, 4, 6, 7)
(1, 4, 6, 7)
(1, 4, 6, 7)
(1, 4, 6, 7)
(1, 4, 6, 7)
(1, 4, 6, 7)
(1, 4, 6, 7)
(1, 4, 6, 7)
(1, 4, 6, 7)
(1, 4, 6, 7)
(1, 4, 6, 7)
(1, 4, 6, 7)
(1, 4, 6, 7)
(1, 4, 6, 7)
(1, 4, 6, 7)
(1, 4, 6, 7)
(1, 4, 6, 7)
(1, 4, 6, 7)
(1, 4, 6, 7)
(1, 4, 6, 7)
(1, 4, 6, 7)
(1, 4, 6, 7)
(1, 4, 6, 7)
(1, 4, 6, 7)
(1, 4, 6, 7)
(1, 4, 6, 7)
(2, 4, 6, 7)
(2, 4, 6, 7)
(2, 4, 6, 7)
(2, 4, 6, 7)
(2, 4, 6, 7)
(2, 4, 6, 7)
(2, 4, 6, 7)
(2, 4, 6, 7)
(2, 4, 6, 7)
(2, 4, 6, 7)
(2, 4, 6, 7)
(2, 4, 6, 7)
(2, 4, 6, 7)
(2, 4, 6, 7)
(2, 4, 6, 7)
(2, 4, 6, 7)
(2, 4, 6, 7)
(2, 4, 6, 7)
(2, 4, 6, 7)
(2, 4, 6, 7)
(2, 4, 6, 7)
(2, 4, 6, 7)
(2, 4, 6, 7)
(2, 4, 6, 7)
(2, 4, 6, 7)
(2, 4, 6, 7)
(2, 4, 6, 7)
(2, 4, 6, 7)
(2, 4, 6, 7)
(2, 4, 6, 7)
(2, 4, 6, 7)
(2, 4, 6, 7)
(2, 4, 6, 7)
(2, 4, 6, 7)
(2, 4, 6, 7)
(2, 4, 6, 7)
(2, 4, 6, 7)

In [5]:
c.buffer.states[2].shape

(3, 4, 6, 7)

In [6]:
states, pol, wdl = c.buffer.get_batch(10)

In [7]:
print(*map(len, states))

2 8 9 5 8 7 6 8 4 9


In [8]:
s, p, w = map(torch.from_numpy, (states[0], pol[0], wdl[0]))

In [9]:
s.shape

torch.Size([2, 4, 6, 7])

In [10]:
p

tensor([[0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1.]])

In [11]:
m.net(s)

(tensor([[[0.0793, 0.1484, 0.2431, 0.0523, 0.2157, 0.0940, 0.1672],
          [0.1545, 0.1220, 0.1104, 0.0657, 0.1136, 0.2409, 0.1928]]],
        grad_fn=<SoftmaxBackward0>),
 tensor([[[0.1047, 0.4760, 0.4193],
          [0.4435, 0.1697, 0.3868]]], grad_fn=<SoftmaxBackward0>))

In [12]:
for i in range(400):
    m.train_step(s, p, w)

In [13]:
torch.argmax(p, dim=-1)

tensor([1, 6])

In [14]:
torch.argmax(m.net(s)[0], dim=-1)

tensor([[1, 6]])

In [18]:
m.net(s)

(tensor([[[4.4554e-05, 9.9968e-01, 4.9999e-05, 4.8602e-05, 7.2681e-05,
           6.8695e-05, 3.9700e-05],
          [4.1114e-05, 6.1453e-05, 7.0361e-05, 3.6508e-05, 4.7631e-05,
           4.8998e-05, 9.9969e-01]]], grad_fn=<SoftmaxBackward0>),
 tensor([[[0.7594, 0.0817, 0.1589],
          [0.9772, 0.0131, 0.0097]]], grad_fn=<SoftmaxBackward0>))

In [17]:
len(states)

10